from pydomain.cqrs import (
    MISSING,
    AggregateLockingBehavior,
    Command,
    CommandBus,
    CommandExecutionError,
    CommandHandler,
    CommandResult,
    CQRSError,
    DictLockKeyResolver,
    EmptyCommandResult,
    HandlerAlreadyRegisteredError,
    IdempotencyBehavior,
    IdempotentCommandIgnored,
    IntegrationEvent,
    LockKeyResolver,
    LockProvider,
    LoggingBehavior,
    MessageContext,
    MessageKind,
    MessagePipeline,
    NextHandler,
    NoHandlerRegisteredError,
    PipelineBehavior,
    ProcessedCommandStore,
    Projection,
    ProjectionStore,
    Query,
    QueryBus,
    QueryHandler,
    QueryResult,
    ValidationBehavior,
)
from pydomain.cqrs.saga import (  # noqa: F401 — re-exported for convenience
    CompensationRecord,
    Saga,
    SagaConfigurationError,
    SagaError,
    SagaHandlerNotFoundError,
    SagaManager,
    SagaRegistry,
    SagaRepository,
    SagaState,
    SagaStateError,
    SagaStatus,
    StepRecord,
)
from pydomain.cqrs.unit_of_work import AbstractUnitOfWork, UnitOfWork
from pydomain.ddd import (
    AggregateRoot,
    AndSpecification,
    ConcurrencyError,
    DomainError,
    DomainEvent,
    DomainService,
    Entity,
    Factory,
    IdGenerator,
    NotSpecification,
    OrSpecification,
    ReconstitutionFactory,
    Repository,
    Specification,
    SpecificationError,
    Uuid7Generator,
    ValueObject,
)
from pydomain.es import (
    # Projection and Subscription intentionally NOT re-exported here:
    #   - Projection: would shadow pydomain.cqrs.Projection (Protocol)
    #   - Subscription: internal dataclass, users consume via SubscriptionRunner
    CheckpointStore,
    DuplicateCommandError,
    EventSourcedAggregateRoot,
    EventSourcedRepository,
    EventStore,
    EventStream,
    StreamNotFoundError,
)
from pydomain.infrastructure.subscription import SubscriptionRunner

__all__ = [
    # DDD
    "AggregateRoot",
    "AndSpecification",
    "ConcurrencyError",
    "DomainError",
    "DomainEvent",
    "DomainService",
    "Entity",
    "Factory",
    "IdGenerator",
    "NotSpecification",
    "OrSpecification",
    "ReconstitutionFactory",
    "Repository",
    "Specification",
    "SpecificationError",
    "Uuid7Generator",
    "ValueObject",
    # CQRS
    "AggregateLockingBehavior",
    "Command",
    "CommandBus",
    "CommandExecutionError",
    "CommandHandler",
    "CommandResult",
    "CQRSError",
    "DictLockKeyResolver",
    "EmptyCommandResult",
    "HandlerAlreadyRegisteredError",
    "IdempotencyBehavior",
    "IdempotentCommandIgnored",
    "IntegrationEvent",
    "LockKeyResolver",
    "LockProvider",
    "LoggingBehavior",
    "MISSING",
    "MessageContext",
    "MessageKind",
    "MessagePipeline",
    "NextHandler",
    "NoHandlerRegisteredError",
    "PipelineBehavior",
    "ProcessedCommandStore",
    "Projection",
    "ProjectionStore",
    "Query",
    "QueryBus",
    "QueryHandler",
    "QueryResult",
    "ValidationBehavior",
    # Saga
    "CompensationRecord",
    "Saga",
    "SagaConfigurationError",
    "SagaError",
    "SagaHandlerNotFoundError",
    "SagaManager",
    "SagaRegistry",
    "SagaRepository",
    "SagaState",
    "SagaStateError",
    "SagaStatus",
    "StepRecord",
    # ES
    "CheckpointStore",
    "DuplicateCommandError",
    "EventSourcedAggregateRoot",
    "EventSourcedRepository",
    "EventStore",
    "EventStream",
    "StreamNotFoundError",
    "SubscriptionRunner",
    # Infrastructure
    "AbstractUnitOfWork",
    "UnitOfWork",
]
